import React from 'react';
import { IconButton, Box } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { useNavigate } from 'react-router-dom';
import contactInfo from '../constants/contactInfo';
import { useLanguage } from '../context/LanguageContext';

const TermsAndConditionsPage = () => {
  const { language, t } = useLanguage();
  const isTamil = language === 'tamil';
  const navigate = useNavigate();
  return (
    <Box sx={{ px: { xs: 1, sm: 2 }, py: { xs: 1.5, sm: 2 }, maxWidth: 600, mx: 'auto' }}>
      <IconButton aria-label="back" onClick={() => navigate(-1)} sx={{ mb: 1 }}>
        <ArrowBackIcon />
      </IconButton>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: 14, lineHeight: 1.2 }}>{t('termsAndConditions')}</h1>
      <Box sx={{ color: 'text.secondary', fontSize: { xs: '0.98rem', sm: '1.05rem' }, lineHeight: 1.7 }}>
        {isTamil ? (
          <>
            <p>இந்த ஆவணம் தகவல் தொழில்நுட்ப சட்டம், 2000 மற்றும் அதன் கீழ் உள்ள விதிகளின்படி உருவாக்கப்பட்ட ஒரு மின்னணு ஆவணமாகும். இந்த மின்னணு பதிவு கணினி அமைப்பால் உருவாக்கப்படுகிறது மற்றும் எந்தவொரு உடல் அல்லது டிஜிட்டல் கையொப்பங்களும் தேவையில்லை.</p>
            <p>இந்த தளம் (<b>sriammansmartstore.in</b>) மற்றும் மொபைல் செயலி <b>ஸ்ரீ அம்மன் ஸ்மார்ட் ஸ்டோர்</b> நிறுவனத்தால் நிர்வகிக்கப்படுகிறது.</p>
            <p>நீங்கள் இந்த தளத்தைப் பார்வையிடுவதன் மூலமோ அல்லது பொருட்களை வாங்குவதன் மூலமோ, இந்த விதிமுறைகள் மற்றும் நிபந்தனைகளை ஏற்றுக்கொள்கிறீர்கள்.</p>
            
            <Box sx={{ background: '#f8f9fa', borderRadius: 2, p: 2, my: 2 }}>
              <b>இந்த தளத்தை அணுகுவது அல்லது பயன்படுத்துவது இந்த விதிமுறைகள் மற்றும் நிபந்தனைகளுக்கு உங்கள் முழு சம்மதத்தைக் குறிக்கிறது. தொடர்வதற்கு முன் தயவுசெய்து கவனமாகப் படிக்கவும்.</b>
            </Box>

            <h2 style={{ fontSize: '1.15rem', fontWeight: 600, marginTop: 24, color: '#333' }}>பொது விதிமுறைகள்</h2>
            <ul style={{ marginLeft: 24, marginBottom: 16 }}>
              <li>சேவைகளைப் பயன்படுத்த, நீங்கள் பதிவு செய்யும் போதும் அதற்குப் பின்னரும் உண்மையான, துல்லியமான மற்றும் முழுமையான தகவல்களை வழங்க ஒப்புக்கொள்கிறீர்கள்.</li>
              <li>தளத்தில் உள்ள படங்கள், தகவல்கள் மற்றும் தயாரிப்பு விவரங்கள் எங்கள் நிறுவனத்தின் அறிவுசார் சொத்தாகும்.</li>
              <li>சேவைகளைப் பெறுவது தொடர்பான கட்டணங்களை முறையாகச் செலுத்த ஒப்புக்கொள்கிறீர்கள்.</li>
              <li>சட்டவிரோதமான, ஒழுக்கக்கேடான அல்லது இந்திய சட்டங்களால் தடைசெய்யப்பட்ட எந்தவொரு நோக்கத்திற்காகவும் இந்த தளத்தைப் பயன்படுத்தக்கூடாது.</li>
              <li>வாடிக்கையாளர் ஆர்டர் சமர்ப்பிக்கும் போது, அது ஒரு சட்டப்பூர்வ ஒப்பந்தமாக ஏற்றுக்கொள்ளப்படுகிறது.</li>
            </ul>

            <h2 style={{ fontSize: '1.15rem', fontWeight: 600, marginTop: 24, color: '#333' }}>சட்டம் & பொறுப்பு</h2>
            <ul style={{ marginLeft: 24, marginBottom: 16 }}>
              <li>இந்த விதிமுறைகள் அனைத்தும் இந்திய சட்டங்களின்படி நிர்வகிக்கப்பட்டு விளக்கப்படும்.</li>
              <li>இந்த விதிமுறைகள் தொடர்பான அனைத்து தகராறுகளும் ஈரோடு மற்றும் தமிழ்நாடு நீதிமன்றங்களின் பிரத்தியேக அதிகார வரம்பிற்கு உட்பட்டவை.</li>
            </ul>

            <Box sx={{ background: '#f8f9fa', borderRadius: 2, p: 2, my: 3 }}>
              <h2 style={{ fontSize: '1.05rem', fontWeight: 600, marginTop: 0, color: '#333' }}>தொடர்புக்கு</h2>
              <p style={{ margin: 0 }}>
                <b>தொலைபேசி:</b> {contactInfo.phone}<br />
                <b>மின்னஞ்சல்:</b> {contactInfo.email}
              </p>
            </Box>
          </>
        ) : (
          <>
            <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <b>sriammansmartstore.in</b> ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").</p>
            <p>The Platform is owned by <b>Sri Amman Smart Store</b>, a company incorporated under the Companies Act, 1956 with its registered office at 8, Nataraj Street, Kasipalayam, Erode, India (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').</p>
            <p>Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.</p>
            <Box sx={{ background: '#f8f9fa', borderRadius: 2, p: 2, my: 2 }}>
              <b>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</b>
            </Box>
            <h2 style={{ fontSize: '1.15rem', fontWeight: 600, marginTop: 24, color: '#333' }}>General Terms</h2>
            <ul style={{ marginLeft: 24, marginBottom: 16 }}>
              <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration.</li>
              <li>The contents of the Platform and the Services are proprietary to us and are licensed to us.</li>
              <li>You agree to pay us the charges associated with availing the Services.</li>
              <li>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms.</li>
              <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding contract with the Platform Owner.</li>
            </ul>
            <h2 style={{ fontSize: '1.15rem', fontWeight: 600, marginTop: 24, color: '#333' }}>Legal & Liability</h2>
            <ul style={{ marginLeft: 24, marginBottom: 16 }}>
              <li>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</li>
              <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Erode and Tamil Nadu.</li>
            </ul>
            <Box sx={{ background: '#f8f9fa', borderRadius: 2, p: 2, my: 3 }}>
              <h2 style={{ fontSize: '1.05rem', fontWeight: 600, marginTop: 0, color: '#333' }}>Contact</h2>
              <p style={{ margin: 0 }}>
                <b>Phone:</b> {contactInfo.phone}<br />
                <b>Email:</b> {contactInfo.email}
              </p>
            </Box>
          </>
        )}
      </Box>
    </Box>
  );
};

export default TermsAndConditionsPage;
